runtime: php
env: flex

runtime_config:
  document_root: public
  skip_lockdown_document_root: true

beta_settings:
  # Project name - location - database name (Amazon Web Services cloud instance)
  cloud_sql_instances: demo-cloud-app.us-east-2:dbname

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  # App_Key updated for Google Cloud Deployment.
  # Go to Eclipse project and typ "php artisan key:generate --show" to get the project APP_KEY".
  APP_KEY: base64:s8GboDQ7xTouWG2E+SqKzpVJbvuMOQWvUgKsNc5KyKg=

  STORAGE_DIR: /tmp

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate for production use.
# For more information, see: https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 0.25
  memory_gb: 0.50
  disk_size_gb: 0.25
